### ISSUE TITLE
Fix 404 links pulled from GSC

### ISSUE THREAD

**Issue by ZPain8464** [pomerium/documentation#242]
First batch to fix:
- [x] https://github.com/pomerium/documentation/issues/275
- [x] https://github.com/pomerium/documentation/issues/276
- [x] https://github.com/pomerium/documentation/issues/277
- [x] https://github.com/pomerium/documentation/issues/278
- [x] https://github.com/pomerium/documentation/issues/279
- [x] https://github.com/pomerium/documentation/issues/280
- [x] https://github.com/pomerium/documentation/issues/281
- [x] https://github.com/pomerium/documentation/issues/282
- [x] https://github.com/pomerium/documentation/issues/283
- [x] https://github.com/pomerium/documentation/issues/284
- [x] https://github.com/pomerium/documentation/issues/285
- [x] https://github.com/pomerium/documentation/issues/286
- [x] https://github.com/pomerium/documentation/issues/287
- [x] https://github.com/pomerium/documentation/issues/288
- [x] https://github.com/pomerium/documentation/issues/289

**Comment by ZPain8464** [comment]
Lastest crawl on Jan. 8 pulled from [GSC](https://search.google.com/search-console/index/drilldown?resource_id=sc-domain%3Apomerium.com&item_key=CAMYDSAC)

**Comment by ZPain8464** [comment]
#284 is being crawled, but it's a link included in a `kubectl` command. I think that's why GSC is flagging it as 404. Aside from this link, this batch all redirects all links to the correct pages now.
