### ISSUE TITLE
Fix 404s from GSC - second batch

### ISSUE THREAD

**Issue by ZPain8464** [pomerium/documentation#302]
- [ ] https://github.com/pomerium/documentation/issues/293
- [ ] https://github.com/pomerium/documentation/issues/295
- [ ] https://github.com/pomerium/documentation/issues/296
- [ ] https://github.com/pomerium/documentation/issues/297
- [ ] https://github.com/pomerium/documentation/issues/298
- [ ] https://github.com/pomerium/documentation/issues/299
- [ ] https://github.com/pomerium/documentation/issues/300
- [ ] https://github.com/pomerium/documentation/issues/301
